'\" t
.\"     Title: storm-info-provider
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/08/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "STORM\-INFO\-PROVIDE" "1" "10/08/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
storm-info-provider \- StoRM component which configure and update the storage information published on BDII
.SH "SYNOPSIS"
.sp
\fB/usr/libexec/storm\-info\-provider\fR [options] configure|get\-static\-ldif|get\-update\-ldif [options]
.SH "DESCRIPTION"
.sp
StoRM Info Provider is the component of StoRM in charge of feeding resource BDII with information on the Grid Storage Element and the status of its Storage Areas\&. It produces ldif files populated by gatering information from StoRM BackEnd\&.
.sp
StoRM Info Provider is the following runnable Python script:
.sp
\fB/usr/libexec/storm\-info\-provider\fR
.sp
which can be executed by specifying one of these three actions:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
\fBconfigure\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
\fBget\-static\-ldif\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
\fBget\-update\-ldif\fR
.RE
.sp
\fBconfigure\fR
.sp
The configure action installs/creates all the necessary files to make BDII able to retrieve information from StoRM service and publish them by following the needed GLUE specifications\&. It\(cqs automatically re\-run during StoRM service YAIM configuration\&. Knowing that, by default, the BDII uses the following three directories to obtain information sources:
.sp
.if n \{\
.RS 4
.\}
.nf
/var/lib/bdii/gip/ldif
/var/lib/bdii/gip/provider
/var/lib/bdii/gip/plugin
.fi
.if n \{\
.RE
.\}
.sp
These directories are specified as configuration parameters in the BDII\(cqs configuration (see http://gridinfo\&.web\&.cern\&.ch/developers/resource\-bdii)\&. StoRM info provider configure action, by default, creates the provider, plugin and static LDIF file for both GLUE v1\&.3 and GLUE v2 specifications:
.sp
.if n \{\
.RS 4
.\}
.nf
/var/lib/bdii/gip/plugin/storm\-glue13\-plugin
/var/lib/bdii/gip/provider/storm\-glue13\-provider
/var/lib/bdii/gip/static/storm\-glue13\-static\&.ldif
/var/lib/bdii/gip/plugin/storm\-glue2\-plugin
/var/lib/bdii/gip/provider/storm\-glue2\-provider
/var/lib/bdii/gip/static/storm\-glue2\-static\&.ldif
.fi
.if n \{\
.RE
.\}
.sp
The configure action creates also several configuration files, used by the providers scripts:
.sp
.if n \{\
.RS 4
.\}
.nf
/etc/storm/info\-provider/glite\-info\-glue2\-service\-storm\-endpoint\-webdav\&.conf
/etc/storm/info\-provider/glite\-info\-glue13\-service\-storm\&.conf
/etc/storm/info\-provider/glite\-info\-glue2\-service\-storm\-endpoint\-srm\&.conf
/etc/storm/info\-provider/glite\-info\-glue2\-service\-storm\&.conf
.fi
.if n \{\
.RE
.\}
.sp
\fBget\-static\-ldif\fR
.sp
The get\-static\-ldif action can be used to obtain the static LDIF of a particular GLUE specification version\&. This output is the same content of the LDIF file saved into /var/lib/bdii/gip/static directory during configure execution\&.
.sp
\fBget\-update\-ldif\fR
.sp
The get\-update\-ldif action can be used to obtain the LDIF that updates the BDII information (for example the information about free/used space for a storage area)\&. It\(cqs used, by default, by the scripts saved into /var/lib/bdii/gip/plugin directory, created launching the info provider script with configure\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Print usage information\&.
.RE
.PP
\fB\-v\fR=\fILOG_LEVEL\fR
.RS 4
Set the logging level\&. Values:
\fI10\fR
(DEBUG),
\fI20\fR
(INFO),
\fI30\fR
(WARNING) or
\fI40\fR
(ERROR)\&. Default value:
\fI20\fR
(INFO)\&.
.RE
.PP
\fB\-o\fR=\fILOG_FILENAME\fR
.RS 4
Redirect log messages to a file\&. LOG_FILENAME contains the file path\&.
.RE
.SH "CONFIGURE-OPTIONS"
.PP
\fB\-f\fR=\fIFILEPATH\fR
.RS 4
Specify an alternative path to the file that contains the last StoRM related YAIM variables\&. Default value:
\fI/etc/storm/info\-provider/storm\-yaim\-variables\&.conf\fR\&.
.RE
.sp
\fB\-g\fR=\fIglue13|glue2|all\fR Specify the format of your published information: GLUE v1\&.3, GLUE v2 or both\&. Default value: \fIall\fR\&.
.SH "GET-STATIC-LDIF-OPTIONS OR GET-UPDATE-LDIF-OPTIONS"
.sp
\fB\-f\fR=\fIFILEPATH\fR Specify an alternative path to the file that contains the last StoRM related YAIM variables\&. Default value: \fI/etc/storm/info\-provider/storm\-yaim\-variables\&.conf\fR\&.
.sp
\fB\-g\fR=\fIglue13|glue2\fR Specify the format of your published information: GLUE v1\&.3 or GLUE v2\&. Default value: \fIglue2\fR\&.
.SH "FILES"
.PP
\fB/usr/libexec/storm\-info\-provider\fR
.RS 4
The StoRM info provider main script\&.
.RE
.PP
\fB/etc/storm/info\-provider/templates/glite\-info\-glue2\-service\-storm\-endpoint\-srm\&.conf\&.template\fR
.RS 4
The template file used to define the SRM endpoint (Glue v2)\&.
.RE
.PP
\fB/etc/storm/info\-provider/templates/glite\-info\-glue2\-service\-storm\&.conf\&.template\fR
.RS 4
The template file used to define the StoRM storage service (Glue v2)\&.
.RE
.PP
\fB/etc/storm/info\-provider/templates/glite\-info\-glue13\-service\-storm\&.conf\&.template\fR
.RS 4
The template file used to define the StoRM storage service (Glue v1\&.3)\&.
.RE
.SH "EXAMPLES"
.sp
StoRM Info Provider provides the integration between StoRM storage service and resource BDII\&. This integration is initialized automatically by launching YAIM configuration\&. First of all, YAIM StoRM exports all the necessary variables into /etc/storm/info\-provider/storm\-yaim\-variables\&.conf\&. Then, it launches the configure action like follow:
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/libexec/storm\-info\-provider configure
.fi
.if n \{\
.RE
.\}
.sp
As already said above, the default path for "\-f" option is /etc/storm/info\-provider/storm\-yaim\-variables\&.conf and the Glue version specified by "\-g" is "all" by default (both Glue v1\&.3 and Glue v2)\&.
.sp
To reconfigure only Glue v2 information:
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/libexec/storm\-info\-provider configure \-g glue2
.fi
.if n \{\
.RE
.\}
.sp
To increase log verbosity:
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/libexec/storm\-info\-provider \-v 10 configure
.fi
.if n \{\
.RE
.\}
.sp
To use another site info configuration file:
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/libexec/storm\-info\-provider configure \-f <your\-site\-info\&.conf>
.fi
.if n \{\
.RE
.\}
.sp
To get the Glue v2 static information used by BDII run:
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/libexec/storm\-info\-provider get\-static\-ldif
.fi
.if n \{\
.RE
.\}
.sp
or
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/libexec/storm\-info\-provider get\-static\-ldif \-g glue13
.fi
.if n \{\
.RE
.\}
.sp
for the Glue v1\&.3 format\&.
.sp
To get the current update information (Glue v2) of your StoRM storage service run:
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/libexec/storm\-info\-provider get\-update\-ldif
.fi
.if n \{\
.RE
.\}
.sp
or
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/libexec/storm\-info\-provider get\-update\-ldif \-g glue13
.fi
.if n \{\
.RE
.\}
.sp
for the Glue v1\&.3 format\&.
.sp
The logging information of get\-static\-ldif and get\-update\-ldif actions are appended to BDII\(cqs log file: /var/log/bdii/bdii\-update\&.log\&.
.SH "AUTHOR"
.sp
Enrico Vianello <enrico\&.vianello@cnaf\&.infn\&.it>
.SH "COPYING"
.sp
Copyright (c) Members of the EGEE Collaboration\&. 2004\&. See the beneficiaries list for details on the copyright holders\&.
.sp
Licensed under the Apache License, Version 2\&.0 (the "License"); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.sp
www\&.apache\&.org/licenses/LICENSE\-2\&.0: http://www\&.apache\&.org/licenses/LICENSE\-2\&.0
.sp
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
