#!/bin/bash

# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2006-2010.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Used kB
#
function get_used_size_kb () {

  used=`/usr/bin/curl -s http://$4:$5/info/status/$1 | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^used-space/ {print $2}'`
  if [ -z ${used} ]; then
    echo "ERROR: the command /usr/bin/curl -s http://$4:$5/info/status/$1 return no value; check storm info service status."
    exit 1
  fi  

  if [ ${used} -gt 0 ]; then
    # Quota on
    if [ "$3" == "true" ]; then
      # convert in kB (base 10)
      used=$((${used}*1024/1000))
    # Quota off
    else
      # convert in kB (base 10)
      used=$((${used}/1000))
    fi
  fi

  echo "INFO: used in kb - $used"

  export $2=${used}

  return 0

}

#
# Used GB
#
function get_used_size_gb () {

  used=`/usr/bin/curl -s http://$4:$5/info/status/$1 | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^used-space/ {print $2}'`
  if [ -z ${used} ]; then
    echo "ERROR: the command /usr/bin/curl -s http://$4:$5/info/status/$1 return no value; check storm info service status."
    exit 1
  fi

  if [ ${used} -gt 0 ]; then
    # Quota on
    if [ "$3" == "true" ]; then
      # convert in GB (base 10)
      used=$((${used}*1024/(1000*1000*1000)))
    # Quota off
    else
      # convert in GB (base 10)
      used=$((${used}/(1000*1000*1000)))
    fi
  fi

  echo "INFO: used in gb - $used"

  export $2=${used}

  return 0

}

#
# Free kB
#
function get_free_size_kb () {

  free=`/usr/bin/curl -s http://$4:$5/info/status/$1 | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^free-space/ {print $2}'`
  if [ -z ${free} ]; then
    echo "ERROR: the command /usr/bin/curl -s http://$4:$5/info/status/$1 return no value; check storm info service status."
    exit 1
  fi

  if [ ${free} -gt 0 ]; then
    # Quota on
    if [ "$3" == "true" ]; then
      # convert in kB (base 10)
      free=$((${free}*1024/1000))
    # Quota off
    else
      # convert in kB (base 10)
      free=$((${free}/1000))
    fi
  fi

  echo "INFO: free in kb - $free"

  export $2=${free}

  return 0

}

#
# Free GB
#
function get_free_size_gb () {

  free=`/usr/bin/curl -s http://$4:$5/info/status/$1 | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^free-space/ {print $2}'`
  if [ -z ${free} ]; then
    echo "ERROR: the command /usr/bin/curl -s http://$4:$5/info/status/$1 return no value; check storm info service status."
    exit 1
  fi

  if [ ${free} -gt 0 ]; then
    # Quota on
    if [ "$3" == "true" ]; then
      # convert in GB (base 10)
      free=$((${free}*1024/(1000*1000*1000)))
    # Quota off
    else
      # convert in GB (base 10)
      free=$((${free}/(1000*1000*1000)))
    fi
  fi

  echo "INFO: free in gb - $free"

  export $2=${free}

  return 0

}

#
# Total kB
#
function get_total_size_kb () {

  total=`/usr/bin/curl -s http://$4:$5/info/status/$1 | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^total-space/ {print $2}'`
  if [ -z ${total} ]; then
    echo "ERROR: the command /usr/bin/curl -s http://$4:$5/info/status/$1 return no value; check storm info service status."
    exit 1
  fi

  if [ ${total} -gt 0 ]; then
    # Quota on
    if [ "$3" == "true" ]; then
      # convert in kB (base 10)
      total=$((${total}*1024/1000))
    # Quota off
    else
      # convert in kB (base 10)
      total=$((${total}/1000))
    fi
  fi

  echo "INFO: total in kb - $total"

  export $2=${total}

  return 0

}

#
# Total GB
#
function get_total_size_gb () {

  total=`/usr/bin/curl -s http://$4:$5/info/status/$1 | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^total-space/ {print $2}'`
  if [ -z ${total} ]; then
    echo "ERROR: the command /usr/bin/curl -s http://$4:$5/info/status/$1 return no value; check storm info service status."
    exit 1
  fi

  if [ ${total} -gt 0 ]; then
    # Quota on
    if [ "$3" == "true" ]; then
      # convert in GB (base 10)
      total=$((${total}*1024/(1000*1000*1000)))
    # Quota off
    else
      # convert in GB (base 10)
      total=$((${total}/(1000*1000*1000)))
    fi
  fi

  echo "INFO: total in gb - $total"

  export $2=${total}

  return 0

}

###
### Main section
###

  # Source configuration file
  if [ $# = 1 ]; then
    source $1
  else
    exit 1
  fi

  # Source utils file
  UTIL=/opt/glite/yaim/functions/utils/manage_conf
  if [ -e ${UTIL} ]; then
    source ${UTIL}
  else
    exit 1
  fi

  FILE=`mktemp`

  # Prepare need variables
  for SA in ${STORM_STORAGEAREA_LIST}; do

    # Convert case
    SA_UPP=`echo ${SA} | tr '[:lower:]' '[:upper:]'`
    SA_LOW=`echo ${SA} | tr '[:upper:]' '[:lower:]'`

    # Remove DNS-like characters from SA_UPP names
    SA_UPP=`echo ${SA_UPP} | sed -e 's/-//g' -e 's/\.//g'`

    x=STORM_${SA_UPP}_TOKEN;           SA_TOKEN=${!x:-${SA_UPP}_TOKEN}
    x=STORM_${SA_UPP}_QUOTA;           SA_QUOTA=${!x:-false}
    x=STORM_${SA_UPP}_VONAME;          SA_VONAME=${!x:-${SA_LOW}}

    # Get size values on SA_TOKEN (in GB)
    get_used_size_gb ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_BACKEND_HOST} ${STORM_BACKEND_REST_SERVICES_PORT} 
    hash_insert SA_USED_SIZE_GB  ${SA_UPP} ${PARAMETER} 
    get_free_size_gb ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_BACKEND_HOST} ${STORM_BACKEND_REST_SERVICES_PORT}
    hash_insert SA_FREE_SIZE_GB  ${SA_UPP} ${PARAMETER}
    get_total_size_gb ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_BACKEND_HOST} ${STORM_BACKEND_REST_SERVICES_PORT}
    hash_insert SA_TOTAL_SIZE_GB ${SA_UPP} ${PARAMETER}

    # Get size values on SA_TOKEN (in KB)
    get_used_size_kb ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_BACKEND_HOST} ${STORM_BACKEND_REST_SERVICES_PORT}
    hash_insert SA_USED_SIZE_KB ${SA_UPP} ${PARAMETER}
    get_free_size_kb  ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_BACKEND_HOST} ${STORM_BACKEND_REST_SERVICES_PORT}
    hash_insert SA_FREE_SIZE_KB ${SA_UPP} ${PARAMETER}

    # Prepare per-VO and global values
    PERVO_VONAME_INDEX=`echo ${SA_VONAME} | sed -e 's/-//g' -e 's/\.//g'`
    # Add VONAME if missing
    if ! [[ "${PERVO_VONAMES}" =~ "${SA_VONAME}" ]]; then
      PERVO_VONAMES="${PERVO_VONAMES} ${SA_VONAME}"
    fi
    # Sum size values for VONAME and global(in GB)
    x=`hash_find PERVO_USED_SIZE_GB ${PERVO_VONAME_INDEX}`
    y=`hash_find SA_USED_SIZE_GB ${SA_UPP}`
    hash_insert PERVO_USED_SIZE_GB ${PERVO_VONAME_INDEX} $((x+y))
    let GLOBAL_USED_SIZE_GB+=$y

    x=`hash_find PERVO_FREE_SIZE_GB ${PERVO_VONAME_INDEX}`
    y=`hash_find SA_FREE_SIZE_GB ${SA_UPP}`
    hash_insert PERVO_FREE_SIZE_GB ${PERVO_VONAME_INDEX} $((x+y))
    let GLOBAL_FREE_SIZE_GB+=$y

    x=`hash_find PERVO_TOTAL_SIZE_GB ${PERVO_VONAME_INDEX}`
    y=`hash_find  SA_TOTAL_SIZE_GB ${SA_UPP}`
    hash_insert PERVO_TOTAL_SIZE_GB ${PERVO_VONAME_INDEX} $((x+y))
    let GLOBAL_TOTAL_SIZE_GB+=$y

    # Sum size values for VONAME (in KB)
    x=`hash_find PERVO_USED_SIZE_KB ${PERVO_VONAME_INDEX}`
    y=`hash_find SA_USED_SIZE_KB ${SA_UPP}`
    hash_insert PERVO_USED_SIZE_KB ${PERVO_VONAME_INDEX} $((x+y))
    let GLOBAL_USED_SIZE_KB+=$y

    x=`hash_find PERVO_FREE_SIZE_KB ${PERVO_VONAME_INDEX}`
    y=`hash_find SA_FREE_SIZE_KB ${SA_UPP}`
    hash_insert  PERVO_FREE_SIZE_KB ${PERVO_VONAME_INDEX} $((x+y))
    let GLOBAL_FREE_SIZE_KB+=$y

  done

  #==========================================================
  # Create GlueSE entries

  cat >> ${FILE} << EOF
dn: GLUE2StorageServiceCapacityId=${STORM_FRONTEND_PUBLIC_HOST}/capacity/online,GLUE2ServiceId=${STORM_FRONTEND_PUBLIC_HOST},GLUE2GroupId=resource,o=glue
objectClass: GLUE2StorageServiceCapacity
GLUE2StorageServiceCapacityId: ${STORM_FRONTEND_PUBLIC_HOST}/capacity/online
GLUE2StorageServiceCapacityType: online
GLUE2StorageServiceCapacityTotalSize: $((GLOBAL_TOTAL_SIZE_GB))
GLUE2StorageServiceCapacityFreeSize: $((GLOBAL_FREE_SIZE_GB))
GLUE2StorageServiceCapacityUsedSize: $((GLOBAL_USED_SIZE_GB))
GLUE2StorageServiceCapacityReservedSize: 0

EOF
  #==========================================================

  #==========================================================
  # Create Glue2Share entries

  for SA in ${STORM_STORAGEAREA_LIST}; do

    # Convert case
    SA_UPP=`echo ${SA} | tr '[:lower:]' '[:upper:]'`
    SA_LOW=`echo ${SA} | tr '[:upper:]' '[:lower:]'`

    # Remove DNS-like characters from SA_UPP names
    SA_UPP=`echo ${SA_UPP} | sed -e 's/-//g' -e 's/\.//g'`

    x=STORM_${SA_UPP}_ACCESSPOINT;     SA_ACCESSPOINT=${!x:-/${SA_LOW}}
    x=STORM_${SA_UPP}_TOKEN;           SA_TOKEN=${!x}
    x=STORM_${SA_UPP}_VONAME;          SA_VONAME=${!x:-${SA_LOW}}
    x=STORM_${SA_UPP}_STORAGECLASS;    SA_STORAGECLASS=${!x:-${STORM_STORAGECLASS}}
    x=STORM_${SA_UPP}_SERVINGSTATE;    SA_SERVING_STATE=${!x:-/${SA_SERVING_STATE}}
    # Convert in uppercase
    SA_STORAGECLASS=`echo ${SA_STORAGECLASS} | tr '[:lower:]' '[:upper:]'`

    # Check the STORAGECLASS
    SA_RETENTION_POLICY="replica"                                         # default
    SA_ACCESS_LATENCY="online"                                            # default
    SA_INSTALLED_ONLINE_CAPACITY=`hash_find SA_TOTAL_SIZE_GB ${SA_UPP}`   # default
    SA_INSTALLED_NEARLINE_CAPACITY=0                                      # default
    if ! [ -z "${SA_STORAGECLASS}" ]; then
      case ${SA_STORAGECLASS} in
        "T1D0")
          SA_RETENTION_POLICY="custodial"
          SA_ACCESS_LATENCY="nearline"
          SA_INSTALLED_ONLINE_CAPACITY=0
          SA_INSTALLED_NEARLINE_CAPACITY=`hash_find SA_TOTAL_SIZE_GB ${SA_UPP}`
          ;;
        "T1D1")
          SA_RETENTION_POLICY="custodial"
          SA_ACCESS_LATENCY="online"
          SA_INSTALLED_ONLINE_CAPACITY=`hash_find SA_TOTAL_SIZE_GB ${SA_UPP}`
          SA_INSTALLED_NEARLINE_CAPACITY=0
          ;;
        "T0D1")
          SA_RETENTION_POLICY="replica"
          SA_ACCESS_LATENCY="online"
          SA_INSTALLED_ONLINE_CAPACITY=`hash_find SA_TOTAL_SIZE_GB ${SA_UPP}`
          SA_INSTALLED_NEARLINE_CAPACITY=0
          ;;
        *)
          SA_RETENTION_POLICY="replica"
          SA_ACCESS_LATENCY="online"
          SA_INSTALLED_ONLINE_CAPACITY=`hash_find SA_TOTAL_SIZE_GB ${SA_UPP}`
          SA_INSTALLED_NEARLINE_CAPACITY=0
          ;;
      esac
    fi

    cat >> ${FILE} << EOF
dn: GLUE2StorageShareCapacityID=${STORM_FRONTEND_PUBLIC_HOST}/${SA_LOW}/capacity,GLUE2ShareId=${STORM_FRONTEND_PUBLIC_HOST}/${SA_LOW},GLUE2ServiceId=${STORM_FRONTEND_PUBLIC_HOST},GLUE2GroupId=resource,o=GLUE
GLUE2StorageShareCapacityTotalSize: $((`hash_find SA_TOTAL_SIZE_GB ${SA_UPP}`))
GLUE2StorageShareCapacityFreeSize: $((`hash_find SA_FREE_SIZE_GB ${SA_UPP}`))
GLUE2StorageShareCapacityUsedSize: $((`hash_find SA_USED_SIZE_KB ${SA_UPP}`))
GLUE2StorageShareCapacityReservedSize:  $((`hash_find SA_TOTAL_SIZE_GB ${SA_UPP}`))

EOF

  done

#EOF

#  done
  #==========================================================

  # Print built file
  cat ${FILE}
  rm -f ${FILE}

  # Exit with success
  exit 0
