#!/bin/bash

# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2006-2010.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Helper script for the SRM/StoRM service publisher
# First argument is init to set variables
#                   status to check the status

case "$1" in
  init)

    version=2.2.0
    echo GLITE_INFO_SERVICE_ENDPOINT=httpg://${STORM_FRONTEND_PUBLIC_HOST}:${STORM_FRONTEND_PORT}${STORM_FRONTEND_PATH}
    echo GLITE_INFO_SERVICE_VERSION=$version
    exit
    ;;
  
  status)

    #stat=`/sbin/service storm-backend status`
    stat=`ls /var/run/storm-backend.pid &> /dev/null`
    rc=$?

    echo -n "The StoRM Backend server is "
    [[ $rc != 0 ]] && echo -n "not "
    echo "running"
    [[ $rc = 0 ]]
    exit $?
    ;;

  *)

    echo "Usage: glite-info-service-storm <init|status>"
    exit 1
    ;;

esac
