#!/usr/bin/python 

import sys
import getopt

__version__ = "1.0.0"

m={'-u':'used-space',
'-f':'free-space',
'-r':'reserved-space',
'-t':'total-space',
'-a':'available-space'}

s={'used-space':'', 
'free-space':'',
'reserved-space':'',
'total-space':'',
'available-space':''}

if __name__=="__main__":

  try:
    opts, args = getopt.getopt(sys.argv[1:], "u:f:r:t:a:")
  except getopt.GetoptError, err:
    # print help information and exit:
    print str(err) 
    sys.exit(2)

  for o, a in opts:
    if o in m.keys():
      s[m[o]]=int((int(a)*(1000*1000*1000))/(1024*1024*1024))
    else:
      sys.exit(2) 

  print s
