name: StoRM Info Provider tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libldap2-dev libpython3-dev libc6-dev libsasl2-dev
          python -m pip install --upgrade pip
          pip install pytest-cov mock coverage python-ldap
      - name: Run coverage
        working-directory: ./src
        run: |
          pytest --cov-report xml --cov=. tests/
          coverage html
          ls
      - name: Get Coverage
        uses: orgoro/coverage@v3
        if: github.event_name == 'pull_request'
        with:
          coverageFile: ./src/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v5
        with:
          name: assets-for-download
          path: ./src/htmlcov
